# Navigation Links
main:
  - name: About
    url: /#about
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Outputs
    url: /#outputs
    weight: 30
  - name: Members
    url: /#members
    weight: 40
  - name: Project
    url: /#project
    weight: 50
